#pragma once

#define PLAYER_DEFAULT_MPV_HWDEC "auto-safe"
#define PLAYER_DEFAULT_MPV_CACHE "yes"
#define PLAYER_DEFAULT_MPV_CACHE_PAUSE_INITIAL "yes"
#define PLAYER_DEFAULT_MPV_CACHE_PAUSE_WAIT "1"
#define PLAYER_DEFAULT_MPV_DEMUXER_READAHEAD_SECS "5"
#define PLAYER_DEFAULT_MPV_STREAM_BUFFER_SIZE "4MiB"
#define PLAYER_DEFAULT_MPV_VIDEO_SYNC "display-resample"
#define PLAYER_EMPTY_STREAM_LABEL "Select"
#define PLAYER_STREAM_INFO_TOOLTIP "Show stream info"
#define PLAYER_STARTING_STREAM_STATUS "Starting stream"
