#include "player_style.h"

#include <gtk/gtk.h>

char *player_style_build_footer_css(void)
{
    return g_strdup(
        ".player-footer .overlay-icon-button,"
        ".player-footer button.overlay-icon-button {"
        "  background: transparent;"
        "  background-color: transparent;"
        "  background-image: none;"
        "  border: none;"
        "  border-color: transparent;"
        "  outline-color: transparent;"
        "  box-shadow: none;"
        "  color: rgba(255, 255, 255, 0.88);"
        "  min-width: 26px;"
        "  min-height: 24px;"
        "  padding: 4px 5px;"
        "}"
        ".player-footer .overlay-icon-button:hover,"
        ".player-footer button.overlay-icon-button:hover {"
        "  background: rgba(255, 255, 255, 0.14);"
        "  background-image: none;"
        "  color: white;"
        "}"
        ".player-footer .player-refresh-button,"
        ".player-footer button.player-refresh-button {"
        "  min-width: 20px;"
        "  min-height: 22px;"
        "  padding: 3px;"
        "}"
        ".player-footer .volume-mute-button {"
        "  margin-right: 0;"
        "}"
        ".player-footer scale.volume-scale,"
        ".player-footer .volume-scale {"
        "  margin-left: 0;"
        "  margin-right: 0;"
        "  padding-left: 0;"
        "  padding-right: 0;"
        "  outline: none;"
        "  outline-color: transparent;"
        "  box-shadow: none;"
        "}"
        ".player-footer scale.volume-scale:hover,"
        ".player-footer scale.volume-scale:focus,"
        ".player-footer scale.volume-scale:active,"
        ".player-footer .volume-scale:hover,"
        ".player-footer .volume-scale:focus,"
        ".player-footer .volume-scale:active {"
        "  outline: none;"
        "  outline-color: transparent;"
        "  box-shadow: none;"
        "}"
        ".player-footer scale.volume-scale trough {"
        "  background: rgba(255, 255, 255, 0.20);"
        "  background-color: rgba(255, 255, 255, 0.20);"
        "  background-image: none;"
        "  min-height: 3px;"
        "}"
        "scale.volume-scale trough,"
        ".volume-scale trough,"
        "scale.volume-scale > trough,"
        ".volume-scale > trough {"
        "  background: rgba(255, 255, 255, 0.20);"
        "  background-color: rgba(255, 255, 255, 0.20);"
        "  background-image: none;"
        "  min-height: 3px;"
        "}"
        "scale.volume-scale > trough > highlight,"
        ".volume-scale > trough > highlight,"
        ".player-footer scale.volume-scale trough highlight,"
        ".player-footer scale.volume-scale:hover trough highlight,"
        ".player-footer scale.volume-scale:focus trough highlight,"
        ".player-footer scale.volume-scale:active trough highlight,"
        ".player-footer .volume-scale trough highlight,"
        ".player-footer .volume-scale:hover trough highlight,"
        ".player-footer .volume-scale:focus trough highlight,"
        ".player-footer .volume-scale:active trough highlight,"
        ".player-footer scale.volume-scale trough fill,"
        ".player-footer scale.volume-scale:hover trough fill,"
        ".player-footer scale.volume-scale:focus trough fill,"
        ".player-footer scale.volume-scale:active trough fill,"
        ".player-footer .volume-scale trough fill,"
        ".player-footer .volume-scale:hover trough fill,"
        ".player-footer .volume-scale:focus trough fill,"
        ".player-footer .volume-scale:active trough fill,"
        ".player-footer scale.volume-scale highlight,"
        ".player-footer scale.volume-scale:hover highlight,"
        ".player-footer scale.volume-scale:focus highlight,"
        ".player-footer scale.volume-scale:active highlight,"
        ".player-footer .volume-scale highlight,"
        ".player-footer .volume-scale:hover highlight,"
        ".player-footer .volume-scale:focus highlight,"
        ".player-footer .volume-scale:active highlight,"
        ".player-footer scale.volume-scale fill,"
        ".player-footer scale.volume-scale:hover fill,"
        ".player-footer scale.volume-scale:focus fill,"
        ".player-footer scale.volume-scale:active fill,"
        ".player-footer .volume-scale fill,"
        ".player-footer .volume-scale:hover fill,"
        ".player-footer .volume-scale:focus fill,"
        ".player-footer .volume-scale:active fill {"
        "  background: rgba(255, 255, 255, 0.72);"
        "  background-color: rgba(255, 255, 255, 0.72);"
        "  background-image: none;"
        "  box-shadow: none;"
        "}"
        "scale.volume-scale trough highlight,"
        "scale.volume-scale:hover trough highlight,"
        "scale.volume-scale:focus trough highlight,"
        "scale.volume-scale:active trough highlight,"
        ".volume-scale trough highlight,"
        ".volume-scale:hover trough highlight,"
        ".volume-scale:focus trough highlight,"
        ".volume-scale:active trough highlight,"
        "scale.volume-scale highlight,"
        "scale.volume-scale:hover highlight,"
        "scale.volume-scale:focus highlight,"
        "scale.volume-scale:active highlight,"
        ".volume-scale highlight,"
        ".volume-scale:hover highlight,"
        ".volume-scale:focus highlight,"
        ".volume-scale:active highlight,"
        "scale.volume-scale trough fill,"
        ".volume-scale trough fill,"
        "scale.volume-scale fill,"
        ".volume-scale fill {"
        "  background: rgba(255, 255, 255, 0.72);"
        "  background-color: rgba(255, 255, 255, 0.72);"
        "  background-image: none;"
        "  box-shadow: none;"
        "}"
        "scale.volume-scale > trough > slider,"
        ".volume-scale > trough > slider,"
        ".player-footer scale.volume-scale slider,"
        ".player-footer scale.volume-scale:hover slider,"
        ".player-footer scale.volume-scale:focus slider,"
        ".player-footer scale.volume-scale:active slider,"
        ".player-footer .volume-scale slider,"
        ".player-footer .volume-scale:hover slider,"
        ".player-footer .volume-scale:focus slider,"
        ".player-footer .volume-scale:active slider {"
        "  background: rgba(255, 255, 255, 0.95);"
        "  background-color: rgba(255, 255, 255, 0.95);"
        "  background-image: none;"
        "  border-color: rgba(0, 0, 0, 0.45);"
        "  outline: none;"
        "  outline-color: transparent;"
        "  box-shadow: none;"
        "  min-width: 10px;"
        "  min-height: 10px;"
        "  margin-top: -4px;"
        "  margin-bottom: -4px;"
        "  margin-left: 0;"
        "  margin-right: 0;"
        "}"
        "scale.volume-scale slider,"
        "scale.volume-scale:hover slider,"
        "scale.volume-scale:focus slider,"
        "scale.volume-scale:active slider,"
        ".volume-scale slider,"
        ".volume-scale:hover slider,"
        ".volume-scale:focus slider,"
        ".volume-scale:active slider {"
        "  background: rgba(255, 255, 255, 0.95);"
        "  background-color: rgba(255, 255, 255, 0.95);"
        "  background-image: none;"
        "  border-color: rgba(0, 0, 0, 0.45);"
        "  outline: none;"
        "  outline-color: transparent;"
        "  box-shadow: none;"
        "  min-width: 10px;"
        "  min-height: 10px;"
        "  margin-top: -4px;"
        "  margin-bottom: -4px;"
        "  margin-left: 0;"
        "  margin-right: 0;"
        "}"
        "scale trough {"
        "  background-color: rgba(255, 255, 255, 0.20);"
        "  background-image: none;"
        "}"
        "scale trough highlight {"
        "  background-color: rgba(255, 255, 255, 0.72);"
        "  background-image: none;"
        "  border-color: transparent;"
        "  box-shadow: none;"
        "}"
        "scale highlight {"
        "  background-color: rgba(255, 255, 255, 0.72);"
        "  background-image: none;"
        "  border-color: transparent;"
        "  box-shadow: none;"
        "}"
        "scale trough fill {"
        "  background-color: rgba(255, 255, 255, 0.72);"
        "  background-image: none;"
        "  border-color: transparent;"
        "  box-shadow: none;"
        "}"
        "scale fill {"
        "  background-color: rgba(255, 255, 255, 0.72);"
        "  background-image: none;"
        "  border-color: transparent;"
        "  box-shadow: none;"
        "}"
        "scale slider {"
        "  background-color: rgba(255, 255, 255, 0.95);"
        "  background-image: none;"
        "  border-color: rgba(0, 0, 0, 0.45);"
        "  outline: none;"
        "  box-shadow: none;"
        "}"
    );
}

void player_style_install_footer_css(void)
{
    g_autofree char *css = player_style_build_footer_css();
    if (css == NULL) {
        return;
    }

    GtkCssProvider *provider = gtk_css_provider_new();
    gtk_css_provider_load_from_string(provider, css);
    gtk_style_context_add_provider_for_display(
        gdk_display_get_default(),
        GTK_STYLE_PROVIDER(provider),
        GTK_STYLE_PROVIDER_PRIORITY_APPLICATION + 1
    );
    g_object_unref(provider);
}
