#pragma once

#define PLAYER_DEFAULT_MPV_HWDEC "auto-safe"
#define PLAYER_DEFAULT_MPV_CACHE "yes"
#define PLAYER_DEFAULT_MPV_CACHE_PAUSE_INITIAL "yes"
#define PLAYER_DEFAULT_MPV_CACHE_PAUSE_WAIT "3"
#define PLAYER_DEFAULT_MPV_DEMUXER_READAHEAD_SECS "10"
#define PLAYER_DEFAULT_MPV_STREAM_BUFFER_SIZE "8MiB"
#define PLAYER_DEFAULT_MPV_VIDEO_SYNC "audio"
#define PLAYER_EMPTY_STREAM_LABEL "Select"
#define PLAYER_STREAM_INFO_TOOLTIP "Show stream info"
#define PLAYER_STARTING_STREAM_STATUS "Starting stream"
